nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ 'X-Custom-Auth,X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'PATCH' ]
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: [ '%env(string:CORS_ALLOW_ORIGIN)%' ]
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
            hosts: [ '^api\.' ]
